### ISSUE TITLE
osdem.ch not reachable

### ISSUE THREAD

**Issue by sgitkene** [LukasWillin/osdem#1]
Hi, I tried accessing your website, but it seems to be unavailable.

**Comment by LukasWillin** [comment]
Well hello there

This repository was part of a study and is no more maintained. I also dont have access to any newer versions of this software or external ressources.

I kept the code for personal use as I never wouldve expected anyone to visit it.  But in this case I'll be taking it down.

If you have any further questions dont hesitate to reach out to me: lukas.willin@students.fhnw.ch

I wish you the best

**Comment by LukasWillin** [comment]
Closed because no longer maintained
